---
- name: install mysql repo
  yum: name={{ mysql_rpm }} state=present

- name: Install mysqld
  yum: name=mysql-community-server state=present

- name: Start mysqld and set auto start
  systemd: state=started name=mysqld enabled=yes

- name: check alive
  shell: |-
    set -o pipefail
    mysqladmin -u root -p{{ mysql_root_pass }} ping | grep "mysqld is alive"
  register: result
  failed_when: result.rc not in [0, 1]

- name: Get mysql default root password
  shell: |-
    set -o pipefail
    grep "A temporary password is generated" /var/log/mysqld.log | awk '{print $NF}' | tail -n1
  register: mysql_default_password
  when: result.rc == 1

- name: Change mysql default root password
  shell: mysql -u root -p'{{ mysql_default_password.stdout }}' --connect-expired-password -e "set password for root@localhost=password('{{ mysql_root_pass }}');"
  when: result.rc == 1

- name: Install package for mysql_user module
  yum: name={{ item }} state=present
  with_items:
    - MySQL-python

- name: copy hisucon2019-portal.sql
  copy:
    src: hisucon2019-portal.sql
    dest: "/tmp/"
    owner: root
    group: root

- name: Import file.sql similar to mysql -u <username> -p <password> < hostname.sql
  mysql_db:
    state: import
    login_user: root
    login_password: "{{ mysql_root_pass }}"
    name: all
    target: /tmp/hisucon2019-portal.sql

- name: User add
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_pass }}"
    name: hisucon
    password: "{{ mysql_hisucon_pass }}"
    priv: 'hisucon2019_portal.*:ALL'
    state: present

# vim:ft=ansible:
