FROM mysql:5.7

ADD ./Docker/mysql/conf.d/my.cnf /etc/mysql/conf.d/my.cnf
ADD ./Docker/mysql/accesslog.txt /tmp/accesslog.txt
ADD ./Docker/mysql/bulletins.txt /tmp/bulletins.txt
ADD ./Docker/mysql/comments.txt /tmp/comments.txt
ADD ./Docker/mysql/users.txt /tmp/users.txt
ADD ./Docker/mysql/bulletins_star.txt /tmp/bulletins_star.txt
ADD ./Docker/mysql/comments_star.txt /tmp/comments_star.txt
